### ISSUE TITLE
Do you need help?

### ISSUE THREAD

**Issue by nagyesta** [Prominence/openweathermap-java-api#39] opened 2022-08-11 20:38 UTC
Hi,
I have a project where I am planning on using OpenWeatherMap API. I will need to either write a client myself or help an existing project to build one for the community. As I have seen, this repository is the most active from the similar projects, so I wanted to ask whether you have any task where you would consider getting help. I would be happy to contribute some time if I can help out.

Thank you in advance!

**Comment by Prominence** [comment] 2022-08-12 06:56
Hi! Thank you for your interest.
Currently, I'm experimenting(not too often) on dev branch. Not sure whether my approach(make it impossible to create "wrong" request and response model even on compilation stage) is convenient, because the the code is already too bloated I guess. But I'm trying to continue to implement other OWM API requests and improve the existing ones. I hope I'll release the 3.0.0 version soon. Especially with such interest to the project from users :)

If you have any proposals - you are welcome! Thank you.

**Comment by nagyesta** [comment] 2022-08-12 21:45
Hi @Prominence ,
thanks! I have taken a look at the code and I think I see what you mean! I have a couple of ideas:

1. A lot of the boilerplate code (getter, setter, equals, hashCode, toString) could be removed from the model classes using Lombok
2. I think there would be a way to eliminate 90% of the deserializers by using Jackson annotations if the classes were more closely matching the structure of the actual API.
    1. There would be a way to still keep your own view (noticed that you have Temperature, AtmosphericPressure, Humidity in different classes)
    2. This way you could create just one default ObjectMapper for the whole lib (or even allow getting it from Spring for example)
3. Many of the complications around the measurement units could be eliminated if the standard units were used every time you want to return Java objects and convert on client side to the desired measurement unit
4. It might be possible to eliminate some of the duplication/complication around the terminations and the response conversion.
5. It would be great to have unit tests for the API calls using Wiremock for example and previously saved API responses. This would allow you to test some edge cases including the data returned, not just null/not null level assertions.

I could prepare a PR with most of these points to show what I mean (using one of the API endpoints as an example).
What do you think?

**Comment by Prominence** [comment] 2022-08-13 12:03
Hi @nagyesta, thank you for your response.
1. I've been using Lombok in the very first versions, but I removed it later. I don't remember why. Maybe because almost all getters and setters are generated by Intellij IDEA. Or maybe someone just told me that Lombok's "magic" with unspecified and undocumented internal API calls not a good thing.
2. I think a lot about this. The problem is that OWM API is REALLY bad. It can has almost the same response structure but with 1 small difference. And this leads to a new model in my code. Because I've decided to have only these fields in the model that are really returned from an API call. I even thought about model code generation from documentation on OWN site. But again, I'll repeat, their documentation really bad. Some fields are not specified in it. Some has wrong structure. Real responses are differs from documented one's.
Now I decided to decouple code and separate it into different deserializers to make it more flexible. But it is not good now as I thought.
3. Not sure whether it is a good idea to make some computations on client side. The IDEA is just to represent the official OWN API response in an convenient way. And such changes need to be maintained and covered with tests, replacing one complication with another. Also the problem is that different API responses can has different unit of measure by default.
4. Yes, I also think a lot about it. But currently, I have no any good idea how to deal with that.
5. Mocking responses is also one of my goal for the future 3.0.0 release.

Just to clarify, did you make code review on dev or on master branch? There are a lot of changes.

And yes, of course you could prepare a PR with your point of view how it can be enhanced.
Also, just interesting, what features do you need for this library? What do you lack for now? I can maybe prioritize something.

**Comment by nagyesta** [comment] 2022-08-13 12:23
Hi @Prominence ,
thank you for your answer!

I have checked `dev` branch. I quite like your idea of configuring the request parameters and the termination approach, so I will try to keep those no matter what. At the same time, I will try to get a compromise solution for mapping the strange API models to something more usable. I know, Lombok can be a divisive topic, like spaces vs. tabs 😄. In my opinion, it makes a lot of sense to avoid maintaining generated code in these JSON models (or help the developers to see what matters without the noise from all that generated code).
Regarding the measurement units, I have an idea that might be workable. I will prepare a PR then and show what I mean.

> Also, just interesting, what features do you need for this library?

In general, I would only need the current weather API call as I am planning on showing just a simple widget on my UI. If I wanted, I would be able to use what I have in progress, but I am not really in a hurry (it is only a hobby project of mine) and it is an interesting challenge what you have, so I don't mind providing a possible way forward.

I will share something in a few days hopefully!

**Comment by Prominence** [comment] 2022-08-13 12:28
Great, I'll be waiting for your proposal then :)
And again, thanks for your attention to the project!

**Comment by nagyesta** [comment] 2022-08-20 21:33
Hi @Prominence ,
sorry for the delay! I have just pushed a preview of what I wanted to show. Please find the draft PR here: #40 
It needs a lot more work, but the approach is visible at least and I wanted to work even more on it in case you don't like the direction where it is going. I think starting a review form these classes could make sense:
- `*Terminator` classes to see how code duplication was removed
- Going forward to the response types from each `*Terminator` class to see the mapping approach
- Checking the `RequestSettings` and `ApiConfiguration` classes to see how the configuration could be more flexible

Please let me know what you think!

**Comment by Prominence** [comment] 2022-09-30 22:11
Merged #41. Thanks!

**Closed by Prominence** 2022-09-30 22:11 UTC
